### PR TITLE
Updated Structs to reduce slot usage

### PR DESCRIPTION
**Pull request by 0xScratch**
Same as #11

### CODE REVIEW

**Comment by behnamazimi** [comment]
The `finalizeChallenge` tests are failing with these changes. @0xScratch

**Comment by 0xScratch** [comment]
Oh yea, that's probably due to the difference between the structure of struct Challenge in `utils/SydStructures.sol` and within the interface that belongs to `SydChallengerManager.sol`

**Comment by 0xScratch** [comment]
That worked!
Btw, do you need any previous branches in this repo?

**Comment by behnamazimi** [comment]
> That worked! Btw, do you need any previous branches in this repo?

I don't.

**Review by behnamazimi — APPROVED** [review]

**Pull request merged**
